"""
Generate the documentation artefacts from the database and the measurements.

    docs/data-dictionary.md   every table and column, from INFORMATION_SCHEMA
    docs/data-map.md          FHIR element -> norm -> dw, from docs/lineage.py
    docs/erd.md               Mermaid ERDs, from sys.foreign_keys
    docs/performance.md       from docs/performance_results.json

All four are generated because all four are the kind of document that is
accurate on the day it is written and wrong within a month. A data dictionary
maintained by hand is a data dictionary that disagrees with the database, and a
data dictionary that disagrees with the database is worse than none — someone
will trust it.

The prose that cannot be generated — why a column exists, what a mapping
decided — lives in `docs/lineage.py` next to the mapping it explains, and is
verified by tests/test_docs.py against the real schema.

    python docs/build_docs.py
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from db.connection import SqlServerUnavailable, connect, server_description  # noqa: E402
from docs.lineage import MAPPINGS, UNMAPPED_ALLOWED  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

SCHEMA_ORDER = ["raw", "stg", "norm", "dw", "meta"]
SCHEMA_BLURB = {
    "raw": "FHIR JSON exactly as received. Never edited, never deleted.",
    "stg": "Quarantine. Resources that failed validation, with the reason.",
    "norm": "Third normal form. Constraints, keys, referential integrity.",
    "dw": "Kimball dimensional model. Denormalised, surrogate-keyed.",
    "meta": "Load audit.",
}

GENERATED_BANNER = (
    "<!-- Generated by docs/build_docs.py. Edits here are overwritten; the prose\n"
    "     lives in docs/lineage.py and in the SQL files themselves. -->\n"
)


# ---------------------------------------------------------------------------
# Schema introspection
# ---------------------------------------------------------------------------

def fetch_columns(cur) -> list[dict]:
    cur.execute("""
        SELECT s.name  AS table_schema,
               t.name  AS table_name,
               c.name  AS column_name,
               c.column_id,
               ty.name AS data_type,
               c.max_length, c.precision, c.scale, c.is_nullable, c.is_identity,
               CASE WHEN pk.column_id IS NOT NULL THEN 1 ELSE 0 END AS is_primary_key,
               fk.referenced_table,
               dc.definition AS default_definition
        FROM sys.columns AS c
        JOIN sys.tables  AS t  ON t.object_id = c.object_id
        JOIN sys.schemas AS s  ON s.schema_id = t.schema_id
        JOIN sys.types   AS ty ON ty.user_type_id = c.user_type_id
        LEFT JOIN (
            SELECT ic.object_id, ic.column_id
            FROM sys.index_columns AS ic
            JOIN sys.indexes AS i ON i.object_id = ic.object_id AND i.index_id = ic.index_id
            WHERE i.is_primary_key = 1
        ) AS pk ON pk.object_id = c.object_id AND pk.column_id = c.column_id
        LEFT JOIN (
            SELECT fkc.parent_object_id, fkc.parent_column_id,
                   CONCAT(OBJECT_SCHEMA_NAME(fkc.referenced_object_id), '.',
                          OBJECT_NAME(fkc.referenced_object_id)) AS referenced_table
            FROM sys.foreign_key_columns AS fkc
        ) AS fk ON fk.parent_object_id = c.object_id AND fk.parent_column_id = c.column_id
        LEFT JOIN sys.default_constraints AS dc ON dc.object_id = c.default_object_id
        WHERE s.name IN ('raw', 'stg', 'norm', 'dw', 'meta')
        ORDER BY s.name, t.name, c.column_id
    """)
    names = [d[0] for d in cur.description]
    return [dict(zip(names, row, strict=True)) for row in cur.fetchall()]


def fetch_row_counts(cur) -> dict[str, int]:
    cur.execute("""
        SELECT CONCAT(s.name, '.', t.name) AS table_name, SUM(p.rows) AS rows
        FROM sys.tables AS t
        JOIN sys.schemas AS s ON s.schema_id = t.schema_id
        JOIN sys.partitions AS p ON p.object_id = t.object_id AND p.index_id IN (0, 1)
        WHERE s.name IN ('raw', 'stg', 'norm', 'dw', 'meta')
        GROUP BY s.name, t.name
    """)
    return {row[0]: int(row[1]) for row in cur.fetchall()}


def fetch_foreign_keys(cur) -> list[tuple[str, str, str, str]]:
    cur.execute("""
        SELECT CONCAT(OBJECT_SCHEMA_NAME(fk.parent_object_id), '.',
                      OBJECT_NAME(fk.parent_object_id))     AS child,
               CONCAT(OBJECT_SCHEMA_NAME(fk.referenced_object_id), '.',
                      OBJECT_NAME(fk.referenced_object_id)) AS parent,
               fk.name,
               COL_NAME(fkc.parent_object_id, fkc.parent_column_id) AS child_column
        FROM sys.foreign_keys AS fk
        JOIN sys.foreign_key_columns AS fkc ON fkc.constraint_object_id = fk.object_id
        WHERE OBJECT_SCHEMA_NAME(fk.parent_object_id) IN ('norm', 'dw')
        ORDER BY child, parent
    """)
    return [tuple(row) for row in cur.fetchall()]


def fetch_check_constraints(cur) -> dict[str, list[tuple[str, str]]]:
    cur.execute("""
        SELECT CONCAT(OBJECT_SCHEMA_NAME(cc.parent_object_id), '.',
                      OBJECT_NAME(cc.parent_object_id)) AS table_name,
               cc.name, cc.definition
        FROM sys.check_constraints AS cc
        WHERE OBJECT_SCHEMA_NAME(cc.parent_object_id) IN ('raw', 'stg', 'norm', 'dw', 'meta')
        ORDER BY table_name, cc.name
    """)
    grouped = defaultdict(list)
    for table, name, definition in cur.fetchall():
        grouped[table].append((name, definition))
    return grouped


def fetch_indexes(cur) -> dict[str, list[tuple[str, str, bool]]]:
    cur.execute("""
        SELECT CONCAT(s.name, '.', t.name) AS table_name,
               i.name,
               i.type_desc,
               i.is_unique,
               STUFF((SELECT ', ' + c.name
                      FROM sys.index_columns AS ic
                      JOIN sys.columns AS c ON c.object_id = ic.object_id
                                           AND c.column_id = ic.column_id
                      WHERE ic.object_id = i.object_id AND ic.index_id = i.index_id
                        AND ic.is_included_column = 0
                      ORDER BY ic.key_ordinal
                      FOR XML PATH('')), 1, 2, '') AS key_columns
        FROM sys.indexes AS i
        JOIN sys.tables  AS t ON t.object_id = i.object_id
        JOIN sys.schemas AS s ON s.schema_id = t.schema_id
        WHERE s.name IN ('raw', 'norm', 'dw') AND i.name IS NOT NULL
        ORDER BY table_name, i.name
    """)
    grouped = defaultdict(list)
    for table, name, type_desc, is_unique, key_columns in cur.fetchall():
        grouped[table].append((name, f"{type_desc}{' UNIQUE' if is_unique else ''} "
                                     f"({key_columns or 'n/a'})", bool(is_unique)))
    return grouped


def type_label(column: dict) -> str:
    name = column["data_type"]
    if name in ("nvarchar", "nchar", "varchar", "char", "varbinary", "binary"):
        length = column["max_length"]
        if length == -1:
            return f"{name}(max)"
        if name.startswith("n"):
            length //= 2
        return f"{name}({length})"
    if name in ("decimal", "numeric"):
        return f"{name}({column['precision']},{column['scale']})"
    if name in ("datetime2", "time"):
        return f"{name}({column['scale']})"
    return name


# ---------------------------------------------------------------------------
# Data dictionary
# ---------------------------------------------------------------------------

def build_data_dictionary(columns, row_counts, checks, indexes, server) -> str:
    notes = {}
    for mapping in MAPPINGS:
        for target in (mapping.norm_column, mapping.dw_column):
            if target and target.count(".") == 2 and mapping.note:
                notes[target.lower()] = mapping.note
    sources = {}
    for mapping in MAPPINGS:
        for target in (mapping.norm_column, mapping.dw_column):
            if target and target.count(".") == 2:
                sources[target.lower()] = (
                    f"`{mapping.resource}.{mapping.fhir_path}`" if mapping.resource
                    else ("_derived_" if mapping.fhir_path == "derived"
                          else f"_{mapping.fhir_path}_")
                )

    lines = [
        "# Data dictionary", "", GENERATED_BANNER,
        f"Every table and column in the warehouse, read from `sys.columns` on "
        f"{server['edition'].split(' (')[0]} {server['product_version']}.",
        "",
        "The **Source** column traces each field back to the FHIR element it came from; "
        "`docs/data-map.md` shows the same relationship the other way round, from the "
        "resource down. A test asserts the two agree with the database.",
        "",
        "> Row counts describe the build this file was generated from — see "
        "`metrics.json` for which population that was. Everything else here is "
        "structure and does not move with the data.",
        "",
    ]

    by_table = defaultdict(list)
    for column in columns:
        by_table[f"{column['table_schema']}.{column['table_name']}"].append(column)

    for schema in SCHEMA_ORDER:
        tables = sorted(t for t in by_table if t.startswith(f"{schema}."))
        if not tables:
            continue
        lines += [f"## `{schema}`", "", SCHEMA_BLURB.get(schema, ""), ""]
        for table in tables:
            rows = row_counts.get(table, 0)
            lines += [f"### `{table}`", ""]
            if table in UNMAPPED_ALLOWED:
                lines += [f"_{UNMAPPED_ALLOWED[table]}_", ""]
            lines += [f"**{rows:,} rows.**", "",
                      "| Column | Type | Null | Key | Source | Notes |",
                      "|---|---|---|---|---|---|"]
            for column in by_table[table]:
                qualified = f"{table}.{column['column_name']}".lower()
                key = []
                if column["is_primary_key"]:
                    key.append("PK")
                if column["referenced_table"]:
                    key.append(f"FK &rarr; `{column['referenced_table']}`")
                if column["is_identity"]:
                    key.append("identity")
                lines.append(
                    f"| `{column['column_name']}` | `{type_label(column)}` | "
                    f"{'yes' if column['is_nullable'] else '**no**'} | "
                    f"{'<br>'.join(key) or ''} | {sources.get(qualified, '')} | "
                    f"{notes.get(qualified, '')} |"
                )
            lines.append("")

            if checks.get(table):
                lines += ["**Constraints**", ""]
                for name, definition in checks[table]:
                    lines.append(f"- `{name}` — `{definition}`")
                lines.append("")
            if indexes.get(table):
                lines += ["**Indexes**", ""]
                for name, description, _ in indexes[table]:
                    lines.append(f"- `{name}` — {description}")
                lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Data map
# ---------------------------------------------------------------------------

def build_data_map(server) -> str:
    lines = [
        "# Data map", "", GENERATED_BANNER,
        "FHIR element &rarr; `norm` column &rarr; `dw` column, for every field the "
        "warehouse carries.",
        "",
        "Generated from `docs/lineage.py`, which is checked against the live schema by "
        "`tests/test_docs.py`: a column added without an entry here fails the build, and "
        "an entry naming a column that no longer exists fails it too. A data map nobody "
        "verifies is a data map that was accurate once.",
        "",
        "`[0]` means the warehouse takes the first of a repeating element; `[*]` means it "
        "takes all of them, into a child table.",
        "",
        "## Lineage",
        "",
        "```mermaid",
        "flowchart LR",
        "    subgraph SOURCE[FHIR R4]",
        "        P[Patient]",
        "        E[Encounter]",
        "        C[Condition]",
        "        O[Observation]",
        "        PR[Procedure]",
        "        M[MedicationRequest]",
        "        PA[Practitioner]",
        "        OR[Organization]",
        "    end",
        "    subgraph RAW[raw]",
        "        R[fhir_resource<br/>NVARCHAR MAX + ISJSON]",
        "    end",
        "    subgraph NORM[norm - 3NF]",
        "        NP[patient<br/>patient_address]",
        "        NE[encounter]",
        "        NC[condition]",
        "        NO[observation<br/>observation_component]",
        "        NPR[procedure]",
        "        NM[medication_request]",
        "        NA[practitioner<br/>organization<br/>+ identifier tables]",
        "        NT[code_system<br/>code_concept]",
        "    end",
        "    subgraph DW[dw - Kimball star]",
        "        DP[DimPatient<br/>SCD Type 2]",
        "        DD[DimDate]",
        "        DA[DimProvider<br/>DimOrganization]",
        "        DC[DimDiagnosis<br/>DimProcedure<br/>DimMedication"
        "<br/>DimObservationCode<br/>DimEncounterType]",
        "        FE[FactEncounter]",
        "        FO[FactObservation]",
        "        FM[FactMedicationOrder]",
        "        FD[FactEncounterDiagnosis]",
        "        FP[FactProcedure]",
        "    end",
        "    Q[stg.ingest_rejects]",
        "",
        "    P --> R",
        "    E --> R",
        "    C --> R",
        "    O --> R",
        "    PR --> R",
        "    M --> R",
        "    PA --> R",
        "    OR --> R",
        '    R -->|"invalid"| Q',
        "    R --> NP",
        "    R --> NE",
        "    R --> NC",
        "    R --> NO",
        "    R --> NPR",
        "    R --> NM",
        "    R --> NA",
        "    R --> NT",
        "    NP --> DP",
        "    NA --> DA",
        "    NT --> DC",
        "    NE --> FE",
        "    NO --> FO",
        "    NM --> FM",
        "    NC --> FD",
        "    NPR --> FP",
        "    DP --> FE",
        "    DA --> FE",
        "    DC --> FE",
        "    DD --> FE",
        "    FE --> FO",
        "    FE --> FM",
        "    FE --> FD",
        "    FE --> FP",
        "```",
        "",
        "## Field-level map",
        "",
    ]

    by_resource = defaultdict(list)
    for mapping in MAPPINGS:
        by_resource[mapping.resource or "(derived and generated)"].append(mapping)

    for resource in sorted(by_resource, key=lambda r: (r.startswith("("), r)):
        lines += [f"### {resource}", "",
                  "| FHIR element | `norm` | `dw` | Notes |", "|---|---|---|---|"]
        for mapping in by_resource[resource]:
            fhir = "_derived_" if mapping.fhir_path == "derived" else f"`{mapping.fhir_path}`"
            lines.append(
                f"| {fhir} | {f'`{mapping.norm_column}`' if mapping.norm_column else '—'} | "
                f"{f'`{mapping.dw_column}`' if mapping.dw_column else '—'} | {mapping.note} |"
            )
        lines.append("")

    lines += [
        "---", "",
        f"Generated against {server['edition'].split(' (')[0]} {server['product_version']}.",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# ERD
# ---------------------------------------------------------------------------

def _entity(name: str) -> str:
    return name.split(".", 1)[1]


def build_erd(columns, foreign_keys, server) -> str:
    by_table = defaultdict(list)
    for column in columns:
        by_table[f"{column['table_schema']}.{column['table_name']}"].append(column)

    def diagram(schema: str, title: str) -> list[str]:
        tables = sorted(t for t in by_table if t.startswith(f"{schema}."))
        out = ["```mermaid", "erDiagram"]
        for table in tables:
            out.append(f"    {_entity(table)} {{")
            for column in by_table[table]:
                marker = "PK" if column["is_primary_key"] else (
                    "FK" if column["referenced_table"] else "")
                data_type = type_label(column).replace("(", "_").replace(")", "").replace(",", "_")
                out.append(f"        {data_type} {column['column_name']} {marker}".rstrip())
            out.append("    }")
        seen = set()
        for child, parent, _name, child_column in foreign_keys:
            if not (child.startswith(f"{schema}.") and parent.startswith(f"{schema}.")):
                continue
            key = (child, parent, child_column)
            if key in seen:
                continue
            seen.add(key)
            out.append(f"    {_entity(parent)} ||--o{{ {_entity(child)} : {child_column}")
        out.append("```")
        return [f"## {title}", ""] + out + [""]

    lines = [
        "# Entity relationship diagrams", "", GENERATED_BANNER,
        "Both diagrams are generated from `sys.columns` and `sys.foreign_keys`, so they "
        "show the relationships the engine is actually enforcing rather than the ones "
        "someone meant to create.",
        "",
    ]
    lines += diagram("norm", "`norm` — the normalised transactional model")
    lines += [
        "Every relationship above is a declared foreign key. That is the point of this "
        "layer: it is the only place in the pipeline where an encounter referencing a "
        "patient who does not exist is refused rather than reported on.",
        "",
    ]
    lines += diagram("dw", "`dw` — the dimensional model")
    lines += [
        "Five fact tables around conformed dimensions. `DimPatient` is the only Type 2 "
        "dimension; the facts join to it on a date range rather than on `is_current`, "
        "which is what makes the history mean anything.",
        "",
        "---", "",
        f"Generated against {server['edition'].split(' (')[0]} {server['product_version']}.",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Performance
# ---------------------------------------------------------------------------

def _delta(before: int, after: int) -> str:
    if not before:
        return "n/a"
    change = (after - before) / before * 100
    return f"{change:+.1f}%"


def build_performance(results: dict) -> str:
    server = results["server"]
    lines = [
        "# Performance", "", GENERATED_BANNER,
        "Three queries, each with one specific change, measured before and after.",
        "",
        "**Every number on this page was produced by `analytics/measure_performance.py` "
        "and copied here mechanically.** None of them is an estimate and none is a "
        "percentage chosen because it read well. Re-running that script rewrites this "
        "file; if the numbers change, the file changes.",
        "",
        "## How it was measured",
        "",
        "- **Logical reads is the headline number, not elapsed time.** Elapsed time on a "
        "workstation moves with whatever else the machine is doing. Logical reads counts "
        "8 KB pages the engine touched and is stable across runs for the same plan. A "
        "change that halves elapsed time without moving logical reads made the machine "
        "quieter, not the query cheaper.",
        "- `DBCC DROPCLEANBUFFERS` and `DBCC FREEPROCCACHE` before every measurement. "
        "Without the first, the second run of a query reads pages the first run cached "
        "and every \"after\" looks faster regardless of what changed. Without the second, "
        "the engine reuses a plan compiled against the old statistics.",
        "- **Actual** execution plans (`SET STATISTICS XML ON`), not estimated ones. The "
        "`.sqlplan` files under `docs/plans/` open in SSMS or Azure Data Studio.",
        "",
        "## Environment",
        "",
        "| | |",
        "|---|---|",
        f"| Engine | {server['edition']} {server['product_version']} {server['product_level']} |",
        f"| Host | {results['host']['platform']} |",
        f"| `dw.FactObservation` | {results['fact_observation_rows']:,} rows |",
        f"| `dw.FactEncounter` | {results['fact_encounter_rows']:,} rows |",
        f"| Measured | {results['measured_at_utc']} |",
        "",
    ]

    for key, query in results["queries"].items():
        before, after = query["before"], query["after"]
        # Subtree cost is a small float; scale it so the shared percentage
        # helper is comparing integers of a similar magnitude to the others.
        cost_delta = _delta(before["estimated_subtree_cost"] * 1000,
                            after["estimated_subtree_cost"] * 1000)
        lines += [
            f"## {key} — {query['title']}", "",
            query["question"], "",
            "```sql",
            query["sql"],
            "```",
            "",
            f"**Change applied:** {query['fix']}, built in {query['fix_build_seconds']}s.",
            "",
            "```sql",
            query["fix_sql"],
            "```",
            "",
            "| Measure | Before | After | Change |",
            "|---|---:|---:|---|",
            f"| Logical reads | {before['logical_reads_total']:,} | "
            f"{after['logical_reads_total']:,} | "
            f"{_delta(before['logical_reads_total'], after['logical_reads_total'])} |",
            f"| CPU (ms) | {before['cpu_ms']:,} | {after['cpu_ms']:,} | "
            f"{_delta(before['cpu_ms'], after['cpu_ms'])} |",
            f"| Elapsed (ms) | {before['elapsed_ms']:,} | {after['elapsed_ms']:,} | "
            f"{_delta(before['elapsed_ms'], after['elapsed_ms'])} |",
            f"| Estimated subtree cost | {before['estimated_subtree_cost']} | "
            f"{after['estimated_subtree_cost']} | "
            f"{cost_delta} |",
            f"| Batch mode | {'yes' if before['batch_mode'] else 'no'} | "
            f"{'yes' if after['batch_mode'] else 'no'} | |",
            f"| Rows returned | {before['rows_returned']:,} | {after['rows_returned']:,} | "
            f"{'same' if before['rows_returned'] == after['rows_returned'] else '**DIFFERENT**'} |",
            "",
            "**Logical reads by table**",
            "",
            "| Table | Before | After |",
            "|---|---:|---:|",
        ]
        tables = sorted(set(before["logical_reads_by_table"])
                        | set(after["logical_reads_by_table"]))
        for table in tables:
            lines.append(f"| `{table}` | {before['logical_reads_by_table'].get(table, 0):,} | "
                         f"{after['logical_reads_by_table'].get(table, 0):,} |")

        lines += ["", "**Plan operators, most expensive first**", "",
                  "| | Before | After |", "|---|---|---|"]
        def render_operator(operator):
            if not operator:
                return "—"
            return "`{physical}` ({subtree_cost})".format(**operator)

        depth = max(len(before["top_operators"]), len(after["top_operators"]))
        for i in range(min(depth, 5)):
            b = before["top_operators"][i] if i < len(before["top_operators"]) else None
            a = after["top_operators"][i] if i < len(after["top_operators"]) else None
            lines.append(f"| {i + 1} | {render_operator(b)} | {render_operator(a)} |")

        before_ops = {o["physical"] for o in before["top_operators"]}
        after_ops = {o["physical"] for o in after["top_operators"]}
        gone, arrived = sorted(before_ops - after_ops), sorted(after_ops - before_ops)
        lines += ["", "**What changed in the plan**", ""]
        if gone or arrived:
            if gone:
                lines.append(f"- Gone: {', '.join(f'`{o}`' for o in gone)}")
            if arrived:
                lines.append(f"- Arrived: {', '.join(f'`{o}`' for o in arrived)}")
        else:
            lines.append("- The same operators, at different costs. Recorded as measured.")
        lines += ["",
                  f"Plans: [`{before['plan']}`]"
                  f"({Path(before['plan']).relative_to('docs').as_posix()}) · "
                  f"[`{after['plan']}`]"
                  f"({Path(after['plan']).relative_to('docs').as_posix()})"
                  if before["plan"] and after["plan"] else "",
                  ""]

    lines += [
        "## Indexes",
        "",
        "Every index in `sql/indexes/` carries the query it exists for. An index with no "
        "recorded rationale is one nobody will dare drop, and an unused index is not free: "
        "it is written on every insert, and this warehouse's inserts are the expensive part.",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------

def main() -> int:
    try:
        with connect() as cn:
            cur = cn.cursor()
            columns = fetch_columns(cur)
            row_counts = fetch_row_counts(cur)
            foreign_keys = fetch_foreign_keys(cur)
            checks = fetch_check_constraints(cur)
            indexes = fetch_indexes(cur)
        server = server_description()
    except SqlServerUnavailable as exc:
        print(f"SQL Server unavailable: {exc}", file=sys.stderr)
        return 2

    DOCS.mkdir(parents=True, exist_ok=True)
    written = []

    (DOCS / "data-dictionary.md").write_text(
        build_data_dictionary(columns, row_counts, checks, indexes, server),
        encoding="utf-8", newline="\n")
    written.append("data-dictionary.md")

    (DOCS / "data-map.md").write_text(build_data_map(server), encoding="utf-8", newline="\n")
    written.append("data-map.md")

    (DOCS / "erd.md").write_text(build_erd(columns, foreign_keys, server),
                                 encoding="utf-8", newline="\n")
    written.append("erd.md")

    results_path = DOCS / "performance_results.json"
    if results_path.exists():
        results = json.loads(results_path.read_text(encoding="utf-8"))
        (DOCS / "performance.md").write_text(build_performance(results),
                                             encoding="utf-8", newline="\n")
        written.append("performance.md")
    else:
        print("  (no performance_results.json — run analytics/measure_performance.py)")

    print(f"generated {len(written)} documents at "
          f"{datetime.now(UTC).strftime('%Y-%m-%dT%H:%M:%SZ')}")
    for name in written:
        print(f"  docs/{name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
